# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

resources:
  containers:
  - container: wpilib2022
    image: wpilib/roborio-cross-ubuntu:2022-20.04

variables:
- group: Artifactory-Package-Publish

stages:
- stage: Build
  jobs:
  - job: Linux
    pool:
      vmImage: 'Ubuntu 20.04'

    container: wpilib2022
    
    variables:
      DISPLAY: ':10'

    steps:
      - bash: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          Xvfb :10 &
        displayName: 'Install and start xvfb'
      - task: Gradle@2
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          testRunTitle: Linux
          tasks: 'check'
          options: '-PbuildServer'

  - job: Windows_64_Bit
    pool:
      vmImage: 'windows-2019'

    steps:
      - task: Gradle@2
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          jdkVersionOption: '1.11'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          testRunTitle: Win64
          tasks: 'check'
          options: '-PbuildServer'

  - job: Mac
    pool:
      vmImage: 'macOS-11'
    steps:
      - script: |
          mkdir build
          export JAVA_HOME=`/usr/libexec/java_home -v 11`
        displayName: 'Setup JDK'
      - task: Gradle@2
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          jdkVersionOption: '1.11'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          testRunTitle: MacOS
          tasks: 'check'
          options: '-PbuildServer'

- stage: Publish
  jobs:
  - job: PublishJob
    pool:
      vmImage: 'ubuntu-20.04'

    steps:
# PR Builds
    - task: Gradle@2
      inputs:
        workingDirectory: ''
        gradleWrapperFile: 'gradlew'
        gradleOptions: '-Xmx3072m'
        jdkVersionOption: '1.11'
        tasks: 'publish'
        options: '-PbuildServer'
      condition: and(succeeded(), and(ne(variables['Build.SourceBranch'], 'refs/heads/main'), not(startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))))

# Main Builds
    - task: Gradle@2
      inputs:
        workingDirectory: ''
        gradleWrapperFile: 'gradlew'
        gradleOptions: '-Xmx3072m'
        jdkVersionOption: '1.11'
        tasks: 'publish'
        options: '-PbuildServer'
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
      env:
        RUN_AZURE_ARTIFACTORY_RELEASE: 'TRUE'
        ARTIFACTORY_PUBLISH_USERNAME: $(PublishUserName)
        ARTIFACTORY_PUBLISH_PASSWORD: $(PublishPassword)

# Tagged Builds
    - task: Gradle@2
      inputs:
        workingDirectory: ''
        gradleWrapperFile: 'gradlew'
        jdkVersionOption: '1.11'
        gradleOptions: '-Xmx3072m'
        tasks: 'publish '
        options: '-PreleaseMode -PbuildServer'
      condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
      env:
        RUN_AZURE_ARTIFACTORY_RELEASE: 'TRUE'
        ARTIFACTORY_PUBLISH_USERNAME: $(PublishUserName)
        ARTIFACTORY_PUBLISH_PASSWORD: $(PublishPassword)
