name: Manual Publish

on: 
  workflow_dispatch:
    publish_version:
      description: 'Version to publish. This should be in the form of vYEAR.M.m'
      required: true

jobs:
  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Publish
        run: ./gradlew publish -PbuildServer -PpublishVersion=${{ github.event.inputs.publish_version }}
        env:
          RUN_AZURE_ARTIFACTORY_RELEASE: "TRUE"
          ARTIFACTORY_PUBLISH_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PUBLISH_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
